enum TokenType {
  // Single-character tokens,
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
  COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

  // ONE OR TWO CHARACTER TOKENS,
  BANG, BANG_EQUAL,
  EEQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,

  // LITERALS,
  IDENTIFIER, STRING, NUMBER,

  // KEYWORDS,
  AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
  PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,

  EOF
}